# Generated by Django 5.1.5 on 2025-02-18 08:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='房型id')),
                ('type_name', models.CharField(default='default', max_length=50, unique=True, verbose_name='房型名称')),
                ('capacity', models.PositiveIntegerField(default='2', verbose_name='入住人数')),
                ('base_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='基础价格（元）')),
                ('extra_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='加价（元）')),
                ('introduction', models.TextField(blank=True, verbose_name='房型介绍')),
                ('homestay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_types', to='accounts.homestay', verbose_name='所属民宿')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='房间号')),
                ('floor', models.IntegerField(blank=True, null=True, verbose_name='楼层')),
                ('status', models.CharField(choices=[('available', '空闲'), ('booked', '已预订'), ('check_in', '已入住'), ('maintenance', '维护中'), ('cleaning', '打扫中'), ('prepared', '备房')], default='available', max_length=20, verbose_name='房间状态')),
                ('check_in_time', models.DateTimeField(blank=True, null=True, verbose_name='入住时间')),
                ('check_out_time', models.DateTimeField(blank=True, null=True, verbose_name='退房时间')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='rooms.roomtype', verbose_name='房间类型')),
            ],
            options={
                'ordering': ['room_id'],
            },
        ),
    ]
