# Generated by Django 5.1.5 on 2025-02-20 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_rename_check_in_time_room_expected_check_in_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='expected_check_in',
        ),
        migrations.RemoveField(
            model_name='room',
            name='expected_check_out',
        ),
        migrations.AddField(
            model_name='roomtype',
            name='expected_check_in',
            field=models.TimeField(blank=True, default='14:00:00', null=True, verbose_name='入住时间'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='expected_check_out',
            field=models.TimeField(blank=True, default='12:00:00', null=True, verbose_name='退房时间'),
        ),
    ]
