# Generated by Django 5.1.5 on 2025-03-01 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_remove_room_expected_check_in_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roomtype',
            options={'ordering': ['base_price', 'extra_price']},
        ),
        migrations.RemoveField(
            model_name='room',
            name='floor',
        ),
    ]
