# Generated by Django 5.1.5 on 2025-03-01 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_alter_roomtype_options_remove_room_floor'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_number',
            field=models.CharField(default=1, max_length=20, verbose_name='房间编号'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='room_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='房间id'),
        ),
    ]
