# Generated by Django 5.1.5 on 2025-03-01 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_room_room_number_alter_room_room_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='status',
            new_name='room_status',
        ),
    ]
