# Generated by Django 5.1.5 on 2025-03-03 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_rename_status_room_room_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': [models.Case(models.When(room_status='available', then=0), models.When(room_status='booked', then=1), models.When(room_status='check_in', then=2), models.When(room_status='cleaning', then=3), models.When(room_status='maintenance', then=4), models.When(room_status='prepared', then=5), default=6, output_field=models.IntegerField()), 'room_number']},
        ),
        migrations.AlterField(
            model_name='room',
            name='room_status',
            field=models.CharField(choices=[('available', '空闲'), ('booked', '已预订'), ('check_in', '已入住'), ('cleaning', '打扫中'), ('maintenance', '维护中'), ('prepared', '备房')], default='available', max_length=20, verbose_name='房间状态'),
        ),
    ]
