# Generated by Django 5.1.5 on 2025-03-04 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_alter_room_options_alter_room_room_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='expected_check_in',
            field=models.TimeField(blank=True, null=True, verbose_name='入住时间'),
        ),
        migrations.AddField(
            model_name='room',
            name='expected_check_out',
            field=models.TimeField(blank=True, null=True, verbose_name='退房时间'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.CharField(max_length=20, verbose_name='房号'),
        ),
    ]
