# Generated by Django 5.1.5 on 2025-03-20 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0009_alter_room_room_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomTypeInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_rooms', models.PositiveIntegerField(default=0, verbose_name='当天可售房量')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='当日价格')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='rooms.roomtype')),
            ],
            options={
                'verbose_name': '房型每日库存',
                'verbose_name_plural': '房型每日库存',
                'unique_together': {('room_type', 'date')},
            },
        ),
    ]
