# Generated by Django 5.1.5 on 2025-03-21 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0010_roomtypeinventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='expected_check_in',
        ),
        migrations.RemoveField(
            model_name='room',
            name='expected_check_out',
        ),
        migrations.DeleteModel(
            name='RoomTypeInventory',
        ),
    ]
