# Generated by Django 5.1.5 on 2025-02-20 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': [models.Case(models.When(role='manager', then=0), models.When(role='reception', then=1), models.When(role='cleaner', then=2), default=3, output_field=models.IntegerField()), 'employee_id']},
        ),
    ]
