# Generated by Django 5.1.5 on 2025-02-22 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_employee_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='是否注销'),
        ),
    ]
