# Generated by Django 5.1.5 on 2025-03-04 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0008_room_expected_check_in_room_expected_check_out_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Occupant',
            fields=[
                ('id_card', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='身份证')),
                ('name', models.CharField(max_length=100, verbose_name='入住人姓名')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False, verbose_name='订单id')),
                ('order_status', models.CharField(choices=[('booked', '已预订'), ('checked_in', '已入住'), ('checked_out', '已退房'), ('cancelled', '已取消'), ('finished', '已完成')], default='booked', max_length=20, verbose_name='订单状态')),
                ('customer_name', models.CharField(max_length=100, verbose_name='下单人姓名')),
                ('customer_phone', models.CharField(max_length=11, verbose_name='下单人机号')),
                ('customer_IDcard', models.CharField(max_length=30, verbose_name='下单人身份证')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='订单创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='订单更新时间')),
                ('check_in_time', models.DateTimeField(blank=True, null=True, verbose_name='入住时间')),
                ('check_out_time', models.DateTimeField(blank=True, null=True, verbose_name='退房时间')),
                ('expected_check_in_time', models.DateTimeField(blank=True, null=True, verbose_name='预期到达时间')),
                ('expected_check_out_time', models.DateTimeField(blank=True, null=True, verbose_name='预期离开时间')),
                ('payment_time', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('days', models.PositiveIntegerField(default=1, verbose_name='入住天数')),
                ('room_number_snapshot', models.CharField(blank=True, max_length=50, null=True, verbose_name='房间号(下单时)')),
                ('room_type_snapshot', models.CharField(blank=True, max_length=50, null=True, verbose_name='房型(下单时)')),
                ('is_pay', models.BooleanField(default=False, verbose_name='是否支付')),
                ('amounts', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='订单金额')),
                ('payment_method', models.CharField(blank=True, choices=[('cash', '现金'), ('wechat', '微信'), ('alipay', '支付宝'), ('credit_card', '信用卡'), ('bank_transfer', '银行转账'), ('others', '其他')], default='cash', max_length=20, null=True, verbose_name='支付方式')),
                ('occupants', models.ManyToManyField(blank=True, related_name='orders', to='orders.occupant')),
                ('related_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='orders.order', verbose_name='关联订单')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='rooms.room', verbose_name='房号')),
                ('room_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='rooms.roomtype', verbose_name='房型')),
            ],
        ),
    ]
