# Generated by Django 5.1.5 on 2025-03-09 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amounts',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='订单金额'),
        ),
    ]
