# Generated by Django 5.1.5 on 2025-03-09 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_amounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='check_in_time',
            field=models.DateField(blank=True, null=True, verbose_name='入住时间'),
        ),
        migrations.AlterField(
            model_name='order',
            name='check_out_time',
            field=models.DateField(blank=True, null=True, verbose_name='退房时间'),
        ),
        migrations.AlterField(
            model_name='order',
            name='expected_check_in_time',
            field=models.DateField(blank=True, null=True, verbose_name='预期到达时间'),
        ),
        migrations.AlterField(
            model_name='order',
            name='expected_check_out_time',
            field=models.DateField(blank=True, null=True, verbose_name='预期离开时间'),
        ),
    ]
