# Generated by Django 5.1.5 on 2025-03-11 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_employee_employee_avatar'),
        ('orders', '0003_alter_order_check_in_time_alter_order_check_out_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='homestay',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='accounts.homestay'),
            preserve_default=False,
        ),
    ]
