# Generated by Django 5.1.5 on 2025-03-14 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_employee_employee_avatar'),
        ('orders', '0004_order_homestay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='check_in_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='入住时间'),
        ),
        migrations.AlterField(
            model_name='order',
            name='check_out_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='退房时间'),
        ),
        migrations.AlterField(
            model_name='order',
            name='homestay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='accounts.homestay', verbose_name='所属民宿'),
        ),
    ]
