# Generated by Django 5.1.5 on 2025-03-15 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_check_in_time_alter_order_check_out_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='expected_check_in_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='预期到达时间'),
        ),
        migrations.AlterField(
            model_name='order',
            name='expected_check_out_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='预期离开时间'),
        ),
    ]
