# Generated by Django 5.1.5 on 2025-03-16 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_expected_check_in_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='expected_check_in_date',
            field=models.DateField(blank=True, null=True, verbose_name='预期入住日期'),
        ),
        migrations.AddField(
            model_name='order',
            name='expected_check_in_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='预期入住日期-时间'),
        ),
        migrations.AddField(
            model_name='order',
            name='expected_check_out_date',
            field=models.DateField(blank=True, null=True, verbose_name='预期退房日期'),
        ),
        migrations.AddField(
            model_name='order',
            name='expected_check_out_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='预期退房日期-时间'),
        ),
        migrations.AlterField(
            model_name='order',
            name='expected_check_in_time',
            field=models.TimeField(blank=True, null=True, verbose_name='预期入住时间'),
        ),
        migrations.AlterField(
            model_name='order',
            name='expected_check_out_time',
            field=models.TimeField(blank=True, null=True, verbose_name='预期退房时间'),
        ),
    ]
