# Generated by Django 5.1.5 on 2025-03-20 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_occupants_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='check_in_time',
        ),
        migrations.RemoveField(
            model_name='order',
            name='check_out_time',
        ),
        migrations.AddField(
            model_name='order',
            name='check_in_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='实际入住时间'),
        ),
        migrations.AddField(
            model_name='order',
            name='check_out_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='实际退房时间'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_phone',
            field=models.CharField(max_length=11, verbose_name='下单人手机号'),
        ),
        migrations.AlterField(
            model_name='order',
            name='expected_check_in_time',
            field=models.TimeField(blank=True, null=True, verbose_name='预期到店时间'),
        ),
        migrations.AlterField(
            model_name='order',
            name='expected_check_out_time',
            field=models.TimeField(blank=True, null=True, verbose_name='预期离店时间'),
        ),
    ]
