# Generated by Django 5.1.5 on 2025-03-21 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_remove_order_check_in_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_channel',
            field=models.CharField(blank=True, choices=[('online', '线上支付'), ('in_store', '到店支付'), ('others', '其他')], default='others', max_length=20, null=True, verbose_name='支付渠道'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', '现金'), ('wechat', '微信'), ('alipay', '支付宝'), ('bank_transfer', '银行转账'), ('others', '其他')], default='cash', max_length=20, null=True, verbose_name='支付方式'),
        ),
    ]
